export const EVENTS_DATA = [
  {
    id: 1,
    title: "Tech Conference 2024",
    category: "Technology",
    date: "2024-12-15",
    budget: 150000,
    capacity: 1200,
    organizer: "Big tech company (scary)",
    speakers: 10,
    logistics: [
      { item: "Stage Setup", status: "Completed" },
      { item: "Catering", status: "Pending" },
      { item: "Sound System", status: "In Progress" },
    ],
  },
  {
    id: 2,
    title: "Startup Pitch Night",
    category: "Business",
    date: "2024-11-28",
    budget: 10000,
    capacity: 200,
    organizer: "Alexej Shevcov",
    speakers: 2,
    logistics: [
      { item: "Projector Setup", status: "In Progress" },
      { item: "Refreshments", status: "Completed" },
      { item: "Seating Arrangement", status: "Pending" },
    ],
  },
  {
    id: 3,
    title: "Music Fest 2024",
    category: "Entertainment",
    date: "2024-10-10",
    budget: 300000,
    capacity: 10000,
    organizer: "Morgenstern))))",
    speakers: 1,
    logistics: [
      { item: "Stage Lights", status: "Pending" },
      { item: "Sound Setup", status: "Completed" },
      { item: "Food Trucks", status: "In Progress" },
    ],
  },
];
